### ISSUE TITLE
Clarifying the install instructions

### ISSUE THREAD

**Issue by tmcclintock** [manodeep/Corrfunc#122]
In the "Preferred Install Method" section in the documentation you mention that you can add CC=yourcompiler if doing just the python installation. Having done the full line-by-line installation, it wasn't clear from the docs that you need to add CC=yourcompiler after all lines. This would be a minor fix that might save some confusion in the future :).

**Comment by manodeep** [comment]
How does that look?

**Comment by tmcclintock** [comment]
A lot better. It also turns out that you need to add the flag when you do make tests as well. Otherwise I'm satisfied. Thanks!

**Comment by manodeep** [comment]
Yup. All `make` commands associated with building/compiling need to be followed by `CC=yourcompiler`.

**Comment by manodeep** [comment]
Thanks for raising the issue! The compiler handling is now much better :)
