### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by annehutter** [manodeep/Corrfunc#133]
running build_ext
      ../../common.mk:377: *** python-config (python-config) not found. Please set PYTHON_CONFIG_EXE in "common.mk" to appropriate python-config before installing Corrfunc.2.0.0 .  Stop.

I could resolve this issue by installing `python-devel` on linux (openSuse 42) and python2.7

**Comment by manodeep** [comment]
Fixed with https://github.com/manodeep/Corrfunc/commit/172e07d84a9616a185fc73690be097d8f0a0e1f5
