### ISSUE TITLE
Installation error with numpy header dependency

### ISSUE THREAD

**Issue by annehutter** [manodeep/Corrfunc#134]
make[2]: Entering directory '/home/anne/Programs/Corrfunc/theory/python_bindings'
    gcc  -DVERSION=\"2.0.1\" -DUSE_UNICODE -std=c99 -m64 -g -Wsign-compare -Wall -Wextra -Wshadow -Wunused -fPIC -D_POSIX_SOURCE=200809L -D_GNU_SOURCE -D_DARWIN_C_SOURCE -O3  -ftree-vectorize -funroll-loops -fprefetch-loop-arrays --param simultaneous-prefetches=4  -fopenmp -funroll-loops -march=native -fno-strict-aliasing -Wformat=2  -Wpacked  -Wnested-externs -Wpointer-arith  -Wredundant-decls  -Wfloat-equal -Wcast-qual -Wcast-align -Wmissing-declarations -Wmissing-prototypes  -Wnested-externs -Wstrict-prototypes   -Wno-unused-local-typedefs  -I../../theory/DD -I../../theory/DDrppi -I../../theory/wp -I../../theory/xi -I../../theory/vpf -isystem/usr/include/python2.7 -isystem/usr/include/python2.7 -isystem /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ -I../../io -I../../utils _countpairs.c -c -o _countpairs.o
    _countpairs.c:18:25: fatal error: arrayobject.h: No such file or directory
     #include <arrayobject.h>
                         ^
    compilation terminated.
    Makefile:46: recipe for target '_countpairs.o' failed
    make[2]: *** [_countpairs.o] Error 1
    make[2]: Leaving directory '/home/anne/Programs/Corrfunc/theory/python_bindings'
    Makefile:19: recipe for target 'python_bindings' failed
    make[1]: *** [python_bindings] Error 2
    make[1]: Leaving directory '/home/anne/Programs/Corrfunc/theory'
    Makefile:9: recipe for target 'theory' failed
    make: *** [theory] Error 2

Could be resolved by installing `numpy-devel` on linux. Similar to #133

**Comment by manodeep** [comment]
Fixed with https://github.com/manodeep/Corrfunc/commit/172e07d84a9616a185fc73690be097d8f0a0e1f5
