### ISSUE TITLE
[bug reports] error in Corrfunc documentation

### ISSUE THREAD

**Issue by dptriani** [manodeep/Corrfunc#144]
Hi,
I found these errors while walking through the "Typical Task for Computing Correlation Function:

Calculating Correlation Functions on Simulations
1. In converting 3D pair counts into a correlation function
"_NameError: name 'N' is not defined_"
2. In converting (rp,π) pairs into a projected correlation function 
"_NameError: name 'N' is not defined_"
"_TypeError: DDrppi() missing 1 required positional argument: 'Z1'_"
"_NameError: name 'np' is not defined_"

Calculating Correlation Functions on Mock Catalogs
3. In calculating the projected correlation function, wp(rp)
"_OSError: Could not locate file /mocks/tests/data/Mr19_randoms_northonly.rdcz.ff_"
on the subjected directory, there are 3 files which are:
Mr19_mock_northonly.rdcz.ff
Mr19_mock_northonly.rdcz.dat
Mr19_centers_xyz_forVPF_rmax_10Mpc.txt
4. Calculating the angular correlation function, ω(θ)
"_OSError: Could not locate file /mocks/tests/data/Mr19_randoms_northonly.rdcz.ff_"
"_NameError: name 'np' is not defined_"
"_NameError: name 'nthreads' is not defined_"
"_NameError: name 'rand_N' is not defined_"

**Comment by manodeep** [comment]
Those should be covered by the doctests and the build should be TRAVIS build should be failing. This can only be confidently fixed after #143
