### ISSUE TITLE
Link on RTD broken

### ISSUE THREAD

**Issue by tmcclintock** [manodeep/Corrfunc#145]
I think you need to rebuild your docs on RTD. From the current RTD page, I clicked on the "Edit on Github" [link](https://github.com/manodeep/Corrfunc/blob/origin/master/docs/source/index.rst). This 404ed.

BTW hopefully you put out the paper soon so that I can properly cite you :).

**Comment by manodeep** [comment]
Thanks! Triggered a new build on rtd but the previous build was supposedly fine. Not sure what might be going on

As for the paper, one of the sad side-effects of becoming more senior is the severe lack of time to complete the millions of unfinished tasks :(. Just cite the ascl/ads entry for now - citations are getting picked up by ADS (or I just report them manually).

**Comment by manodeep** [comment]
I rebuilt the docs and the build passed again but the link is still broken. 

I think the difference is that the bad link `https://github.com/manodeep/Corrfunc/blob/origin/master/docs/source/index.rst` has an extra reference to "origin", i.e., the good link should be `https://github.com/manodeep/Corrfunc/blob/master/docs/source/index.rst`

Looks like this is related to [this issue](https://github.com/rtfd/readthedocs.org/issues/1637)

**Comment by tmcclintock** [comment]
Yea you are probably right. I'll close this since it looks like it's not Corrfunc specific.
