### ISSUE TITLE
Incorrect error message w.r.t. gcc requirement + installing at SLAC

### ISSUE THREAD

**Issue by tmcclintock** [manodeep/Corrfunc#147]
I have installed Corrfunc on the machines at SLAC. The stock gcc was 4.4.7. I was able to switch to an up to date gcc by doing `scl enable devtoolset-3 bash` (for anyone in the future that tries this install).

More importantly, the error Corrfunc was giving when I was installing was that it thought I was using an unrecognized CPU that didn't have x86 architecture. This was uninformative, and it took some time to realize that it was the compiler that was the issue. Ideally, if gcc is out of date then the error message should reflect that.

**Comment by manodeep** [comment]
Thanks for reporting this. I think this is at least the second time I have heard about the **old** default compiler at SLAC. The fix could be to add a check for the version (in `common.mk`) and warn for a really old version but I am not sure how to provide a general solution for the range of compilers in place. 

@tmcclintock Do you mind taking a stab at the solution? Happy to work with you...

**Comment by tmcclintock** [comment]
Sure I'll take a look.

**Comment by tmcclintock** [comment]
Fyi I haven't forgotten about this. The SLAC machines are down until January 8. I'll be able to diagnose this after that.

**Comment by manodeep** [comment]
@tmcclintock Thanks!

**Comment by manodeep** [comment]
@tmcclintock Did you have a fix for this issue? Otherwise, are you okay if I close this issue (at least for now)

**Comment by tmcclintock** [comment]
I don't have a fix. Closing now.
