### ISSUE TITLE
required gsl version

### ISSUE THREAD

**Issue by rainwoodman** [manodeep/Corrfunc#163]
What is the minimal required version of gsl?
readme still mentioned gsl from a customized channel. The current anaconda gsl is 2.4.

**Comment by manodeep** [comment]
Corrfunc only requires some integration and interpolation routines from `gsl`. Basically any version should work - but I haven't tested anything specifically. Back in the day, the only `gsl` I could locate on `conda` was this `gsl==2.4` from asmuerer (who used to work at Continuum).

Is this for an equivalent to `requirements.txt`? Specifying `gsl>=2.4` should be safe then

**Comment by rainwoodman** [comment]
I think both mac and linux anaconda has 2.4 now. What about mentioning in the README that ``we tested against 2.4, but previous versions should work as well since Corrfunc only requires some integration and interpolation routines.``

**Comment by manodeep** [comment]
@rainwoodman We added in the recommended gsl version. Closing this issue, please feel free to comment if you have any feedback
