### ISSUE TITLE
wp not working 

### ISSUE THREAD

**Issue by julianakwan** [manodeep/Corrfunc#184]
I get this error message when I run wp (theory) for certain catalogues:

wp_counts = wp(BoxSize, pimax, nthreads, bins, x, y, z,verbose=True)
In gridlink_index_particles_float> Running with [nmesh_x, nmesh_y, nmesh_z]  = 29,29,37.  Time taken =   0.032 sec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.local-u/lib/python2.7/site-packages/Corrfunc-2.2.0-py2.7-linux-x86_64.egg/Corrfunc/theory/wp.py", line 515, in wp
    raise RuntimeError(msg)
RuntimeError: RuntimeError occurred

xi (theory) however, runs on the same set of points:
xi_counts = xi(BoxSize, nthreads, bins, x, y, z)
I can also run wp on a random sample of numbers. 

Also: 

BoxSize = 1491
nthreads = 4
pimax = 100
nbins = 30
bins = np.logspace(-1.,2,nbins+1)

if that helps.

**Comment by lgarrison** [comment]
Thanks for the report!  I don't see any issue in the way you're calling wp, but I do notice that you're running Corrfunc v2.2 (the latest is v2.3).  Maybe try updating?

If that doesn't work, could you provide a minimal working example that demonstrates the issue?

Also, is there any error message other than the one you copied here?  Often there's a more descriptive error message that gets output in addition to the "RuntimeError occurred".

**Comment by manodeep** [comment]
@julianakwan Would it be possible to share the data file that you are using (via dropbox/google drive etc)? We should then be able to reconstruct the issue you are facing

**Comment by manodeep** [comment]
@julianakwan Did you get a chance to debug any further? For instance, could you run the `wp` command-line executable and paste the output here?

**Comment by julianakwan** [comment]
I couldn't reproduce it after I ended that Python session. It was happening on a halo correlation function but not for a random catalogue, so there were no pairs below a certain scale. If it happens again I'll reopen the issue.

**Comment by manodeep** [comment]
@julianakwan Thanks for the update. The symptom you describe sounds quite intriguing - if you do run into that issue again, please do report it.
