### ISSUE TITLE
Gridlink slow for large datasets with copy_particles=False

### ISSUE THREAD

**Issue by lgarrison** [manodeep/Corrfunc#187]
The new option to set `copy_particles=False` in v2.3 is slow in gridlink!  There's a single-threaded sort of particles into cell order.  For a 1 billion particle dataset, this takes 760 seconds instead of 50 seconds if `copy_particles=True`.

I think we can do better than the sort: we've already constructed the cell indices of the particles; we just need to place them there.  The out-of-place algorithm is straightforward (it's what we're already doing when `copy_particles=True`); the in-place algorithm needs some more thought but should be possible.

**Comment by manodeep** [comment]
Agreed. I think we already have the necessary bits for a counting sort

**Comment by manodeep** [comment]
We should be able to adapt [this](https://github.com/travisdowns/sort-bench/blob/master/radix7.cpp) into C

**Comment by manodeep** [comment]
The counting sort, while fast, requires a (temporary) copy of the entire memory area being sorted. May be we should stick with a different sort.

**Comment by lgarrison** [comment]
Superseded by #240.
