### ISSUE TITLE
Units of wp and rbins in projected correlation for mocks

### ISSUE THREAD

**Issue by ulukrasulov** [manodeep/Corrfunc#242]
## General information

- Corrfunc version:2.0.1
- platform:
- installation method (pip/source/other?):pip

## Issue description 
When Calculating the projected correlation for mocks from SDSS data using DDrppi_mocks, what units are the bins and wp returned in (Mpc or Mpc/h)?

Following from the previously raised issue and the documenation notes I have asssumed it to be in Mpc/h. However, comparing the calculated wp to other published papers within the same catalogue properties the results of wp from corrfunc match very well only if the units are in Mpc and not Mpc/h

In addition to this when calculating the wp for theoretical catalogues with x,y,z using Corrfunc.theory.wp the clustering between theoretical catalogues and SDSS catalogues only match when inputting units of Mpc into Corrfunc.theory.wp  for the theoretical catalogues. 

Hence it seems to me that the output of projected clustering for mocks could be in units of Mpc and not Mpc/h? I wanted to double check this issue

**Comment by manodeep** [comment]
Thanks for using Corrfunc and raising this issue. To be clear, the bins are user-input and are *never* modified within `Corrfunc`. I will try to clarify broadly about units in `Corrfunc`.

For `wp` (and all theory pair-counters) are units-agnostic, with the assumption that the bins (+ `pimax` for `wp`,`DDrppi`) are in the same units as the positions. So the units could be `Mpc`, `kpc`, `Mpc/h` etc, and as long as the bins (+ `pimax`) **and** positions are in the same units, the calculation should be fine. 

For `DDrppi_mocks` (and `DDsmu_mocks`), the inputs are assumed to be in `speed-of-light * redshift` and converted to `Mpc/h` units. However, you can perform the conversion yourself and then set the boolean flag `is_comoving_dist=True` and the calculation will be performed in your preferred units. The same caveat as `theory` applies - bins, `pimax` are both assumed to be in the same units as positions. 

Does that clarify the situation?

**Comment by manodeep** [comment]
@ulukrasulov I am assuming this issue is resolved and closing. If you have any further questions, please feel free to re-open this issue

**Comment by manodeep** [comment]
Great - thanks for letting us know
