### ISSUE TITLE
Installation Error (can't find GSL)

### ISSUE THREAD

**Issue by mokidm** [manodeep/Corrfunc#262]
## General information

- Corrfunc version: 2.4.0
- platform:  Linux
- installation method (pip/source/other?): make (as it's mentioned in the "Preferred Install Method" section in README.rst file)

## Issue description 

The installation of Corrfunc could not be completed due to a problem related to GSL library, which apparently cannot be found: 

<img width="501" alt="Image1" src="https://user-images.githubusercontent.com/43304707/137470036-a48e0cb0-1fff-47fb-b216-905bb104bb9d.png">

However, it looks like the library is already installed on the system (it is one of the libraries installed by default with CentOS 7, as can be checked using 'yum info gsl' command): 

<img width="484" alt="Image3" src="https://user-images.githubusercontent.com/43304707/137470833-55a8b4af-198a-4c10-98c4-3607e09ff352.png">

### Expected behavior 

GSL should have been detected as already installed, and therefore the installation of Corrfunc could be completed. 

### Actual behavior

GSL library is not detected as already installed, which results in an installation error.

### What have you tried so far?

I have tried reinstalling GSL library in my personal directory, but it is not an option since I do not have the write permissions needed: 

<img width="492" alt="Image2" src="https://user-images.githubusercontent.com/43304707/137471742-a3089d63-860c-4668-9b12-0aed1e6f15f5.png">

## Minimal failing example

--

**Comment by manodeep** [comment]
@mokidm I am assuming this issue is resolved or not relevant for you. Closing the issue but please feel free to reopen if you need further help
