### ISSUE TITLE
Error in the first correlation value obtained using Corrfunc

### ISSUE THREAD

**Issue by ub2206** [manodeep/Corrfunc#268]
Hello, 
I am an undergraduate student working on the 2-point Angular Correlation value calculation of GRB data. I computed it using two methods, one using the "astroML" library and other using the "Corrfunc" library. As promised, the Corrfunc library is very fast. What takes 45 minutes using astroML takes less than 5 minutes using Corrfunc. But when I obtain the correlation values, the first value in all cases is seemingly very high compared to all other values. That value is coming out reasonably well using the astroML.

I am attaching the plotted correlation values. The plot containing some grey shades in the background is the plot obtained using astroML and one with completely white is the one obtained using Corrfunc. The grey shades can be ignored as it is not required here. It can be just used for distinguishing between two plots. 

![C1](https://user-images.githubusercontent.com/55322420/146210488-9ca562de-2660-444c-8398-a69d199b0167.png)
![C2](https://user-images.githubusercontent.com/55322420/146210533-ded0aa0b-6d70-4e70-9c27-3ba231a20cef.png)
![E2](https://user-images.githubusercontent.com/55322420/146210537-c06f57ae-fd1b-4cb7-a4d3-fcad58a1a76b.png)
![E1](https://user-images.githubusercontent.com/55322420/146210539-cbac2da8-0b7f-44fb-a20c-01e2d9929cb6.png)

If the issue is already resolved, I am sorry for repeating again and request you to kindly guide me through it. 

I have used the `DDtheta_mocks` and the `convert_3d_counts_to_cf` functions in my code. If required, I'd be happy to share the codes.

**Comment by lgarrison** [comment]
I think this is probably a case of self-counts being included in bins that have a minimum separation of 0 (which is the expected behavior although a little surprising sometimes).  It's there to ensure that auto- and cross-correlations yield the same answer.  For your case, I think you probably want to subtract off the self-count in the first bin; that is, subtract `N` from DDtheta.

**Comment by ub2206** [comment]
Thanks a lot for the response and sorry for the late reply from my side. I would just like to confirm just one thing (in case if I am doing anything wrong). 

The `N` is supposed to be subtracted from the _npairs_ of the auto-correlation term only, am I right? The cross-correlation term should be left as it is.

**Comment by lgarrison** [comment]
That's right, it won't make a difference for cross-correlations.  You may also need to subtract it from the RR term if that's computed with pair counts.

**Comment by ub2206** [comment]
Thanks a lot for the solutions. The results are much more accurate and explainable now.

**Comment by manodeep** [comment]
Thanks @lgarrison!

@ub2206 While your issue itself is resolved, since you are effectively computing angular correlation functions over half the sky - it might be worthwhile to check if the runtime improves if you set both `link_in_ra` and `link_in_dec` to `False`.
