### ISSUE TITLE
Some questions about API and integrated test suite

### ISSUE THREAD

**Issue by z20230220** [manodeep/Corrfunc#288]
I found that there is a clerical error about Corrfunc.theory.package in API reference. The first line of Corrfunc.theory.xi reference is "Function to compute the **projected correlation function** in a periodic cosmological box. " but I think the bold part should be "correlation function", not "projected correlation function". 
![fig](https://user-images.githubusercontent.com/125883770/220312669-fab7b944-fc2a-4e2d-a3a9-baa7f859ac98.png)

**Comment by z20230220** [comment]
When I want to test whether I install Corrfunc corectly, I encounter a strange situation. There are some detail infomations as follow:

- corrfunc     2.5.0       py311h3659569_0         conda-forge
- python       3.11.0     he550d4f_1_cpython     conda-forge

It's obvious that the test is failed, but I can import some functions normally such as **wp** and **xi**. What's more, I can use **xi** to calculate my data, it outputs some warnings.

![KW1`BW~YM6{VO@IT~75 4QQ](https://user-images.githubusercontent.com/125883770/220315240-f0785ace-8073-43ae-a526-e921bfaff3a3.png)

![B%5@MR LW3TE893X0H1`THQ](https://user-images.githubusercontent.com/125883770/220320906-7691d864-2524-4e49-a402-50857e2805b9.png)

After that, I change another env, which is used to install nbodykit package, and the test works, though it outputs same warnings too.
- corrfunc     2.3.4       py38hef53783_11           bccp
- nbodykit    0.3.15     py38hfeaa757_6             bccp
- python       3.8.16     he550d4f_1_cpython      conda-forge

![4V0A2DBSZ5TSNT2 7F7@PCY](https://user-images.githubusercontent.com/125883770/220317669-04b7defa-2350-4935-a204-926439522289.png)

It's really confuse me... I want to understand why the test is failed in the first situation. How can I solve these warnings? Should I hope I can solve it to speed up my work. 
Looking forward to your reply

**Comment by lgarrison** [comment]
Thanks for the reports!  I agree the docs are wrong; would you like to submit a PR? I think there's multiple spots in both of these files where it needs to be fixed:

- https://github.com/manodeep/Corrfunc/blob/master/theory/python_bindings/_countpairs.c
- https://github.com/manodeep/Corrfunc/blob/master/Corrfunc/theory/xi.py

If you search "projected" (and skip the ones that are about wp), you should find all of them.

**Comment by lgarrison** [comment]
On the question about the tests, there are a few things going on here.  First, in Corrfunc 2.5, we changed the way the tests are run.  From the command line, try: `python -m pytest --pyargs Corrfunc`. This is documented at https://github.com/manodeep/Corrfunc#method-2-pip-installation, but we forgot to update it at https://corrfunc.readthedocs.io/en/master/install.html?highlight=test#verifying-your-installation-1

If you are interested in opening a PR to fix the docs related to your first question, would you like to also fix these docs? The docs at the second link should be made to match the instructions in the first link.

Second, it looks like Corrfunc is installed via conda in both cases. For best performance, we recommend installing from pip or installing from source. The binaries distributed with conda target a very old instruction set for maximum compatibility, but as a result, they are much slower than a source install.  There's more discussion about optimization here: https://github.com/manodeep/Corrfunc#method-1-source-installation-recommended

**Comment by z20230220** [comment]
Many thanks for your help. My questions are solved faultlessly, everything works well. By the way, this package is really useful and efficient as i've ever seen. I will close the issue, thank you again for the help!
