### ISSUE TITLE
Add a quickstart

### ISSUE THREAD

**Issue by manodeep** [manodeep/Corrfunc#32]
Once the code compiles, the next steps are unclear. Thanks to @aphearin

**Comment by manodeep** [comment]
There is a python snippet now. I am planning to add an ipython notebook demonstrating the codes.

**Comment by aphearin** [comment]
Ideal

**Comment by manodeep** [comment]
Added a quickstart](http://corrfunc.readthedocs.io/en/master/quickstart.html). Takes the user through all 3 interface options for Corrfunc.
