### ISSUE TITLE
CI failure for python 2.7

### ISSUE THREAD

**Issue by manodeep** [manodeep/Corrfunc#320]
## General information

- Corrfunc version: Any
- platform:osx-arm64
- installation method (pip/source/other?): N/A

## Issue description 
The latest [dependabot PR](https://github.com/manodeep/Corrfunc/pull/319) highlighted that CI is not running on osx-arm64 for python2.7. Given that Corrfunc supports python2.7, CI should run

### Expected behavior 
CI runs

### Actual behavior
CI fails on `osx-arm64`. One failure is for `py2.7`, while others are for `py3.7` and `numpy1.16`

### What have you tried so far?
N/A

## Minimal failing example
N/A

@lgarrison Maybe it's time to drop python2.7 and adopt a policy to update the minimum versions of required dependencies.

**Comment by lgarrison** [comment]
+1 for dropping Python 2.7! I usually target non-EOL Python releases (currently 3.8-3.12) in my projects. I doubt we've made any changes that would directly affect the minimum versions of other dependencies, but if we bump the minimum Python version, we might at least need to bump the minimum NumPy version.

**Comment by manodeep** [comment]
I asked on [Twitter](https://x.com/manodeepsinha/status/1807975401203138863) - in case someone has a *real* strong need/justification for python2.7

**Comment by manodeep** [comment]
(Completely biased) Twitter sample of two (so far) suggests that dropping py2.7 is fine

**Comment by manodeep** [comment]
Python2.7 has been dropped from the CI - so this issue is fixed (more accurately, not relevant)
