### ISSUE TITLE
Travis reports failure with v2.0 branch on certain combinations of compilers + python

### ISSUE THREAD

**Issue by manodeep** [manodeep/Corrfunc#40]
I have no idea how this is happening. Must be a race-condition -- tests pass cleanly (10+ times) on my laptop.

**Comment by manodeep** [comment]
Interesting -- wp test fails on my laptop if I run make tests from the root directory but passes if I run make tests in the xi_theory/wp directory

**Comment by manodeep** [comment]
This is a very weird bug -- ``make tests`` in the tests directory runs ``./test_periodic 2`` for the wp test (which fails). Immediately after, if I run ``./test_periodic 2``, then the test passes!

**Comment by manodeep** [comment]
Ahha. ``wp`` is the only code that reorders the input X/Y/Z arrays -- in theory that should be irrelevant since none of the other codes make any assumptions about the input ordering. So, when ``./test_periodic 2`` is run by itself, the tests read the arrays and hand them off whereas when all tests are running the arrays have been read before and used. Still don't know how this could make a difference but clearly it does.

**Comment by manodeep** [comment]
With the re-ordering of tests, all tests fail on linux and the one test on Mac passes! Since the previous failure was with gcc48 on travis, I checked with gcc48 on my laptop and the tests pass. (Side-note, the gcc48 portfile is no longer broken on Macs -- updating README to reflect this.)

Now I need to test on a linux box.

**Comment by manodeep** [comment]
Some cells contain 0 particles -- since I was using malloc, then lattice would have uninitialized values for start and nelements. The sorting would then use these uninitialized values and all hell would break loose. 
Since this bug was not triggering on Mac, I will assume that ``malloc`` on Mac is really ``calloc`` under the hood whereas on Linux ``malloc`` is malloc.

**Comment by manodeep** [comment]
Updated the checks for nelements > 0 and only running sort for non-zero cells (commit f03ad6bc735ffe034e15d280bc6359bef641d9be)

@aphearin This is pretty much in line with how halotools computes the correlation function. Slightly slower than my version in master, but does avoid duplicating the particle memory. Relevant functions/files are ``gridlink_index`` in ``utils/gridlink.c`` and ``xi_theory/wp/countpairs_wp``

**Comment by aphearin** [comment]
Thanks for pointing me to this, @manodeep . I'm partway through my fully-cythonized overhaul, so your timing to point me to the relevant files is good.

**Comment by manodeep** [comment]
@aphearin No problem at all. We might want to re-run the timing tests [here](https://gist.github.com/manodeep/cffd9a5d77510e43ccf0) once your cython version is ready. 

Btw, I discovered that AVX gives up to a factor of 4 speedup in certain cases -- for e.g., large Rmax (although not in the ones we were looking at).
