### ISSUE TITLE
Check if CPU supports AVX at compile time

### ISSUE THREAD

**Issue by manodeep** [manodeep/Corrfunc#48]
In a reasonably likely scenario, the compiler might be capable of supporting AVX instructions but the CPU is not. In such cases, there will be a runtime error: "Illegal instruction". 

I have encountered this already on the TRAVIS OSX Workers and there is manual fix in the `common.mk` file

**Comment by rainwoodman** [comment]
Is AVX enabled on travis?

We got this issue that may be related : 

https://github.com/bccp/nbodykit/issues/534#issuecomment-438751116

**Comment by rainwoodman** [comment]
Is there a way to override REMOVE_AVX -- disabling it even cpuinfo has it?

**Comment by lgarrison** [comment]
Yes, Travis tests the AVX, SSE, and fallback versions of the kernels.

I'm not sure we have a canonical way to disable compiling AVX if the platform supports it (but @manodeep would know for sure).  You might be able to undefine the AVX preprocessor macro by adding `-U__AVX__` to `CFLAGS` in `common.mk`, but even if that worked, you'd probably have to remove or modify `-march=native` flag to prevent other parts of the code from emitting AVX instructions.

One thing to try might be to pass `isa='fallback'` or `'sse'` to the Python invocation even without removing any AVX.  If that works, then it might indicate that you can leave `-march=native` and just try `-U__AVX__`.

**Comment by manodeep** [comment]
If you simply want to disable `AVX`, adding the `-mno-avx` flag (assuming gcc or clang compilers) to `CFLAGS` in `common.mk` will do the trick. 


That crash in https://github.com/bccp/nbodykit/issues/534#issuecomment-438751116 is unusual. I am intrigued as to why the illegal instruction signal is being generated. The code checks the supported cpu features at runtime, and then offloads to the correct kernel appropriately. Is Corrfunc being supplied as a pre-compiled binary?

**Comment by rainwoodman** [comment]
Yes. It is a pre-compiled binary from the conda-bccp-channel. Looks like he also has difficulty installing corrfunc from source on that system.

**Comment by manodeep** [comment]
Ahh okay - then I can see how that illegal instruction might be generated. 

Looked like the pip install succeeded for Corrfunc v2.2.0. Another possibility is that there are multiple Corrfunc versions installed within the environment

**Comment by rainwoodman** [comment]
A stack trace: 

https://github.com/bccp/nbodykit/issues/534#issuecomment-438845062

**Comment by manodeep** [comment]
@rainwoodman I am still not sure where exactly the issue lies (and I read through the discussion on the other repo). Did you guys have any further insights?

**Comment by rainwoodman** [comment]
Not really. It probably just got away with time...

**Comment by manodeep** [comment]
Is it okay then if I closes this issue?

**Comment by rainwoodman** [comment]
Yes, please!

**Comment by manodeep** [comment]
Thanks!
