### ISSUE TITLE
Docs no longer showing API

### ISSUE THREAD

**Issue by manodeep** [manodeep/Corrfunc#77]
`RTD` builds somehow broke and now the API page does not display any more. Wiping and will rebuild in ~ 2 days. H/T @aphearin

**Comment by aphearin** [comment]
Keep me posted.

**Comment by manodeep** [comment]
Needed an `__import__(Corrfunc)`, addition of root directory to `sys.path`. That seemed to solve it. I get warnings from local sphinx about duplicate entries - but the docs build fine locally and on RTD.

**Comment by aphearin** [comment]
Phew!
